### ISSUE TITLE
Fix string command and event error in GDS

### ISSUE THREAD

**Issue by jonathanmichel** [FP-Mission/FS#15]
```
[2021-05-27 16:44:50,907] ERROR in app: Exception on /events [GET]
Traceback (most recent call last):
  File "/home/jonathan/he-arc/FS/fprime-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jonathan/he-arc/FS/fprime-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jonathan/he-arc/FS/fprime-venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/jonathan/he-arc/FS/fprime-venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/jonathan/he-arc/FS/fprime-venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/jonathan/he-arc/FS/fprime/Gds/src/fprime_gds/flask/events.py", line 66, in get
    event.template.format_str % tuple([arg.val for arg in event.args]),
TypeError: 'NoneType' object is not iterable
```

**Comment by jonathanmichel** [comment]
[fixed](https://github.com/FP-Mission/fprime/commit/4298a8670f77c075d59e1f9f8eba8159e6984d7d)
